services:
  gazebo:
    container_name: gazebo
    build:
      context: ./gazebo
      dockerfile: Dockerfile
    user: "1000:1000"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./gazebo/workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/gdm/Xauthority:/root/.Xauthority
      - /run/user/1000/:/run/user/1000/
    networks:
      - rosnet
    privileged: true
    restart: unless-stopped
    command: tail -f /dev/null

  ros2:
    container_name: ros2
    build:
      context: ./ros2
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./ros2/ros2_ws:/root/ros2_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/gdm/Xauthority:/root/.Xauthority
      - /run/user/1000/:/run/user/1000/
    networks:
      - rosnet
    privileged: true
    restart: unless-stopped
    command: tail -f /dev/null

networks:
  rosnet:
    driver: bridge
